# Generated by Django 4.2.2 on 2023-06-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('album', '0002_rename_name_album_album_name_alter_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
            preserve_default=False,
        ),
    ]
